In [16]:
from google.colab import files
uploaded = files.upload()

Saving gender_submission.csv to gender_submission (1).csv
Saving test.csv to test (1).csv
Saving train.csv to train (1).csv

In [37]:
import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

sample = pd.read_csv('gender_submission.csv')
print(train.shape, test.shape)

(891, 12) (418, 11)

In [38]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
train.info()
# Age - has null values ->fillna
# Embarked - 2 nulll ->dropna
# cabin - only 204 ->drop

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [40]:
def engineer_features(df):
  #FamilySize
  df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
  df['Title'] = df['Name'].str.extract(r', ([A-Za-z]+)\.')
  df['Sex_encoded'] = df['Sex'].map({"male": 0, "female": 1})
  return df

In [41]:
engineer_features(train)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,Title,Sex_encoded
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Mrs,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Miss,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Mrs,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Mr,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,Rev,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,Miss,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,Miss,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,Mr,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,Mr,0

In [42]:
print(train[['FamilySize', 'Title', 'Sex_encoded']].head())

   FamilySize Title  Sex_encoded
0           2    Mr            0
1           2   Mrs            1
2           1  Miss            1
3           2   Mrs            1
4           1    Mr            0

In [43]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
 13  Title        890 non-null    object
 14  Sex_encoded  891 non-null    int64
dtypes: float64(2), int64(7), object(6)
memory usage: 104.5+ KB

In [44]:
engineer_features(test)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,Title,Sex_encoded
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,1,Mr,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,2,Mrs,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,1,Mr,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,1,Mr,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,3,Mrs,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,1,Mr,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1,Dona,1
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,1,Mr,0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,1,Mr,0
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,3,Master,0

In [45]:
print(test[['FamilySize', 'Title', 'Sex_encoded']].head())

   FamilySize Title  Sex_encoded
0           1    Mr            0
1           2   Mrs            1
2           1    Mr            0
3           1    Mr            0
4           3   Mrs            1

In [46]:
#Data cleaning
def data_clean(df):
 df.fillna({'Age':df['Age'].median()},inplace=True)
 df.dropna(subset='Embarked', inplace = True)
 df.drop(columns = 'Cabin', inplace=True)

In [47]:
data_clean(train)
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    object
 11  FamilySize   889 non-null    int64
 12  Title        888 non-null    object
 13  Sex_encoded  889 non-null    int64
dtypes: float64(2), int64(7), object(5)
memory usage: 104.2+ KB

In [48]:
data_clean(test)
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Embarked     418 non-null    object
 10  FamilySize   418 non-null    int64
 11  Title        418 non-null    object
 12  Sex_encoded  418 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 42.6+ KB

In [49]:
print(test.columns.tolist())

['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked', 'FamilySize', 'Title', 'Sex_encoded']

In [50]:
# 1 missing title in test
train['Title'].fillna('Unknown', inplace=True)

#1 missing Fare in test
test['Fare'].fillna(test['Fare'].median(), inplace=True)

/tmp/ipykernel_20434/3759888171.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Title'].fillna('Unknown', inplace=True)
/tmp/ipykernel_20434/3759888171.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Fare'].fillna(test['Fare'].median(), inplace=True)

In [51]:
# Features
features = ['Pclass','Age','Fare','Sex_encoded', 'FamilySize' ]

#define X_train, y_train
X_train = train[features]
y_train = train['Survived']

X_test_Kaggle = test[features]

In [52]:
print(X_train.shape, y_train.shape, X_test_Kaggle.shape)

(889, 5) (889,) (418, 5)

In [53]:
# sklearn pipleine
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

#logistic Regression pipeline
lr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])
dt_pipeline = Pipeline([
    ('model',DecisionTreeClassifier(max_depth=2, random_state=42))
])

In [63]:
#train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score,roc_auc_score
X_tr, X_val, y_tr, y_val = train_test_split(X_train,y_train, test_size=0.2, random_state=42)

#fit log REg
lr_pipeline.fit(X_tr, y_tr)

#predict
y_lr_pred = lr_pipeline.predict(X_val)

#accuracy
print(f"Accuracy of Logistic reg pipeline: {accuracy_score(y_val,y_lr_pred):.2f}")
print(f"precision of Logistic reg pipeline: {precision_score(y_val,y_lr_pred):.2f}")
print(f"recall of Logistic reg pipeline: {recall_score(y_val,y_lr_pred):.2f}")
print(f"f1 score of Logistic reg pipeline: {f1_score(y_val,y_lr_pred):.2f}")
print(f"AUC of Logistic reg pipeline: {roc_auc_score(y_val,y_lr_pred):.2f}")

Accuracy of Logistic reg pipeline: 0.79
precision of Logistic reg pipeline: 0.72
recall of Logistic reg pipeline: 0.77
f1 score of Logistic reg pipeline: 0.74
AUC of Logistic reg pipeline: 0.79

In [64]:
# fit Decision tree
dt_pipeline.fit(X_tr, y_tr)

#predict
y_dt_pred = dt_pipeline.predict(X_val)

#accuracy of decision tree pipeline
print(f"Accuracy of decision tree pipeline: {accuracy_score(y_val, y_dt_pred):.2f}")
print(f"precision of decision tree pipeline: {precision_score(y_val,y_dt_pred):.2f}")
print(f"recall of decision tree pipeline: {recall_score(y_val,y_dt_pred):.2f}")
print(f"f1 score of decision tree pipeline: {f1_score(y_val,y_dt_pred):.2f}")
print(f"AUC of decision tree pipeline: {roc_auc_score(y_val,y_dt_pred):.2f}")

Accuracy of decision tree pipeline: 0.80
precision of decision tree pipeline: 0.73
recall of decision tree pipeline: 0.77
f1 score of decision tree pipeline: 0.75
AUC of decision tree pipeline: 0.79

| Metric | Logistic Regression | Decision Tree |
|--------|--------------------:|-------------:|
| Accuracy | 0.79 | 0.80 |
| Precision | 0.72 | 0.73 |
| Recall | 0.77 | 0.77 |
| F1 | 0.74  | 0.75 |
| AUC | 0.79 | 0.79 |

In [66]:
#Kaggle submission
final_predictions = dt_pipeline.predict(X_test_Kaggle)

submission = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived': final_predictions
})
submission.to_csv('submission.csv', index=False)
print(submission.head())

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1