In [1]:
#day 1 titanic dataset reuse  -- describe(), info(), value_counts() — understand your data before doing anything else
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
print(df.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

# Day 2

    1.	Cleaning: dropna, fillna, drop_duplicates, astype — fix the Titanic dataset
    2. String operations with .str — extract, replace, split
    3.	Apply: apply(), map() — transform columns with custom functions

In [6]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [7]:
#Task 1.a) cleaning

#1. drop rows only where Embarked is missing (only 2 rows, not worth filling)
df.dropna(subset='Embarked',inplace=True)

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.3+ KB
None

In [9]:
from numpy import median
#2. fillna
# filling missing Age with the median age

# df['Age'].fillna(df['Age'].median(),inplace=True)  --> old syntax before pandas 3.0


df.fillna({'Age':df['Age'].median()},inplace=True)
# print(df['Age'].median())   #-->28.0

In [10]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 889, dtype: float64

 ### inplace= True
 - For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



1.   df.fillna({'Age':median(df['Age'])},inplace=True)
2.

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.3+ KB
None

In [12]:
print(df['Age'].isnull().sum())

0

In [13]:
#b) drop_duplicates
print(df.duplicated().sum())

0

In [14]:
#if duplicates drop them
df.drop_duplicates(inplace=True)

In [15]:
#c) astype --> converting column data types.
print(df.dtypes)

# Survived  --> categorical variable -->0 or 1, dead or alive
df['Survived']= df['Survived'].astype(pd.CategoricalDtype())

print("Survived variable dtype changed: ",df['Survived'].dtype,"\n")

#Pclass category (1st, 2nd, 3rd class
df['Pclass'] = df['Pclass'].astype('category')
print("Pclass now converted into categorical variable")
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
Survived variable dtype changed:  category

Pclass now converted into categorical variable
PassengerId       int64
Survived       category
Pclass         category
Name             object
Sex              object
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked         object
dtype: object

In [16]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 889, dtype: category
Categories (2, int64): [0, 1]

In [19]:
# TASK 2. String operations with .str — extract, replace, split

#a. Convert all names to lowercase
df['Name'].str.lower()

/tmp/ipykernel_6024/3792704112.py:3: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['Name'].replace().str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 889, dtype: object

In [28]:
#b.Extract just the title (Mr, Mrs, Miss etc.) — it's between ,  and . in each name
df['Title'] = df['Name'].str.extract(r", ([A-Za-z]+)\.")

In [30]:
print(df['Title'].value_counts())

Title
Mr          517
Miss        181
Mrs         124
Master       40
Dr            7
Rev           6
Mlle          2
Major         2
Col           2
Don           1
Mme           1
Ms            1
Sir           1
Lady          1
Capt          1
Jonkheer      1
Name: count, dtype: int64

In [34]:
#c. Check which names contain "Mrs"
  #same as boolean masking np a[a>10]

df[df['Name'].str.contains("Mrs")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Mrs
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Mrs
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,Mrs
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Mrs
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,Mrs
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,Mrs

In [35]:
#Task 3.  Apply: apply(), map() — transform columns with custom functions

1. **map()** → works on a Series, maps each value to a new value
2. **apply()** → works on Series OR DataFrame, applies a function

        1. series.map() ->value substitution on a Series (what we just did with Sex)
        2. series.apply() ->  apply a function to each element of a Series




        1.   DataFrame.map() → apply a function elementwise to whole DataFrame
        2.   DataFrame.apply() → apply a function row-wise or column-wise

1. a. **Task — create an age group column:**
- Instead of raw ages, group them:

- 0-12 → "Child"
- 13-17 → "Teen"
- 18-60 → "Adult"
- 60+ → "Senior"

In [39]:
#apply()
def get_age_group(age):
  if age <13:
    return "Child"

  elif age<18:
    return "Teen"

  elif age<61:
    return "Adult"

  else:
    return "Senior"
df['AgeGroup'] = df['Age'].apply(get_age_group)
print(df['AgeGroup'].value_counts())
print("\n",df['AgeGroup'])

AgeGroup
Adult     755
Child      69
Teen       44
Senior     21
Name: count, dtype: int64

 0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
       ...
886    Adult
887    Adult
888    Adult
889    Adult
890    Adult
Name: AgeGroup, Length: 889, dtype: object

In [40]:
# Map is perfect for simple value substitutions.
#Like converting Sex column from "male"/"female" to 0/1 (which ML models need):

df['Sex_encoded'] = df['Sex'].map({'male':0,"female":1})
print(df['Sex_encoded'].value_counts())

Sex_encoded
0    577
1    312
Name: count, dtype: int64